name: Super-Linter

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Access a secret
        run: echo "Using secret"
        env:
          API_KEY: ${{ secrets.API_KEY }}
